---
# tasks file for mysql
- name: Install setuptools
  yum:
    name: python-setuptools
    state: present

- name: Download PyMySQL tar.gz
  get_url:
    url: https://files.pythonhosted.org/packages/44/39/6bcb83cae0095a31b6be4511707fdf2009d3e29903a55a0494d3a9a2fac0/PyMySQL-0.8.1.tar.gz
    dest: /tmp/PyMySQL-0.8.1.tar.gz
 
- name: Extract PyMySQL tar.gz
  unarchive:
    src: /tmp/PyMySQL-0.8.1.tar.gz
    dest: /tmp/
    remote_src: yes
 
- name: Install PyMySQL
  command:
    cmd: "python setup.py install"
    chdir: "/tmp/PyMySQL-0.8.1"
  
- name: clear mysql
  shell: "yum remove mysql* -y"
  ignore_errors: True

- name: Import CentOS 7 GPG key
  rpm_key:
    state: present
    key: http://mirrors.aliyun.com/centos/RPM-GPG-KEY-CentOS-7

# - name: Install mariadb
#   yum:
#     name: "mariadb*"
#     state: latest

- name: Install mariadb server
  yum:
    name: mariadb-server
    state: latest

- name: Install mariadb client
  yum:
    name: mariadb
    state: latest
 
- name: init maridb
  shell: "rm -rf /var/lib/mysql/*"
 
- name: Start mariadb
  systemd:
    name: mariadb
    state: restarted
    enabled: true

- name: create database
  mysql_db:
    # root登录localhost不允许，需要用套接字登录
    login_unix_socket: /var/lib/mysql/mysql.sock
    # 引用变量名必须加引号，否则报错
    name: "{{ my_db.name }}"
    state: present
    encoding: "{{ my_db.encoding }}"
 
# - name: grant bob;
#   mysql_user:
#     login_unix_socket: /var/lib/mysql/mysql.sock
#     # 引用变量名必须加引号，否则报错
#     name: "{{ my_user.name }}"
#     host: "{{ my_user.host }}"
#     password: "{{ my_user.password }}"
#     priv: "{{ my_user.priv }}"
#     state: present

- name: Grant bob permissions to each host in web_group
  mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: "{{ my_user.name }}"
    host: "{{ hostvars[item].ansible_host }}"
    password: "{{ my_user.password }}"
    priv: "{{ my_user.priv }}"
    state: present
  loop: "{{ groups['web_group'] }}"
  when: groups['web_group'] is defined
