---
# tasks file for mysql
- name: Install setuptools
  yum:
    name: python-setuptools
    state: present

- name: Download PyMySQL tar.gz
  get_url:
    url: https://files.pythonhosted.org/packages/44/39/6bcb83cae0095a31b6be4511707fdf2009d3e29903a55a0494d3a9a2fac0/PyMySQL-0.8.1.tar.gz
    dest: /tmp/PyMySQL-0.8.1.tar.gz
 
- name: Extract PyMySQL tar.gz
  unarchive:
    src: /tmp/PyMySQL-0.8.1.tar.gz
    dest: /tmp/
    remote_src: yes
 
- name: Install PyMySQL
  command:
    cmd: "python setup.py install"
    chdir: "/tmp/PyMySQL-0.8.1"
  
---
- name: 安装 MySQL 5.7 社区版的 RPM 包
  yum:
    name: https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
    state: present

- name: 安装 yum-utils
  yum:
    name: yum-utils
    state: present

- name: 禁用 MySQL 8.0 社区版 repo
  command: yum-config-manager --disable mysql80-community

- name: 启用 MySQL 5.7 社区版 repo
  command: yum-config-manager --enable mysql57-community

- name: 导入 MySQL GPG 密钥 默认的有问题
  rpm_key:
    state: present
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

- name: 安装 MySQL 社区服务器
  yum:
    name: mysql-community-server
    state: present

# - name: 查看 MySQL 版本
#   command: mysql --version
#   register: mysql_version
#   ignore_errors: yes

# - name: 打印 MySQL 版本
#   debug:
#     var: mysql_version.stdout_lines

- name: init mysql
  shell: "rm -rf /var/lib/mysql/*"

- name: 修改my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644

- name: 启动 MySQL 服务
  service:
    name: mysqld
    state: started
    enabled: yes

- name: create database
  mysql_db:
    # root登录localhost不允许，需要用套接字登录
    login_unix_socket: /var/lib/mysql/mysql.sock
    # 引用变量名必须加引号，否则报错
    name: "{{ my_db.name }}"
    state: present
    encoding: "{{ my_db.encoding }}"
 
- name: grant bob;
  mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    # 引用变量名必须加引号，否则报错
    name: "{{ my_user.name }}"
    host: "{{ my_user.host }}"
    password: "{{ my_user.password }}"
    priv: "{{ my_user.priv }}"
    state: present